KTrader: Main.cpp File Reference
Main.cpp File Reference
#include <iostream>
#include "CtpTraderSpi.h"
#include "CSem.h"
Functions
int main ()
Variables
int requestId = 0
char tradeFront [] = "tcp://27.17.62.149:40205"
CSem sem (0)
Function Documentation
int main ()
Definition at line 16 of file Main.cpp.
References CThostFtdcTraderApi::CreateFtdcTraderApi(), CThostFtdcTraderApi::Init(), CThostFtdcTraderApi::Join(), CThostFtdcTraderApi::RegisterFront(), CThostFtdcTraderApi::RegisterSpi(), CtpTraderSpi::ReqQryDepthMarketData(), CThostFtdcTraderApi::SubscribePrivateTopic(), CThostFtdcTraderApi::SubscribePublicTopic(), THOST_TERT_RESTART, and tradeFront.
          {
    CThostFtdcTraderApi* pUserApi = CThostFtdcTraderApi::CreateFtdcTraderApi();
    CtpTraderSpi* pUserSpi = new CtpTraderSpi(pUserApi);
    pUserApi->RegisterSpi((CThostFtdcTraderSpi*)pUserSpi);          // Ê≥®ÂÜå‰∫ã‰ª∂Á±ª
    pUserApi->SubscribePublicTopic(THOST_TERT_RESTART);                 // Ê≥®ÂÜåÂÖ¨ÊúâÊµÅ
    pUserApi->SubscribePrivateTopic(THOST_TERT_RESTART);              // Ê≥®ÂÜåÁßÅÊúâÊµÅ
    pUserApi->RegisterFront(tradeFront);                            // Ê≥®ÂÜå‰∫§ÊòìÂâçÁΩÆÂú∞ÂùÄ
    pUserSpi->ReqQryDepthMarketData("ru1501");
    pUserApi->Init();
    //todo
    pUserApi->Join();
    //pUserApi->Release();
}
Variable Documentation
int requestId = 0
Definition at line 8 of file Main.cpp.
CSem sem(0)
char tradeFront[] = "tcp://27.17.62.149:40205"
Definition at line 12 of file Main.cpp.