EasyQuant: CtpTraderSpi Class Reference
CtpTraderSpi Class Reference
#include <CtpTraderSpi.h>
Public Member Functions
CtpTraderSpi (CThostFtdcTraderApi *api)
virtual void OnFrontConnected ()
当客户端与交易后台建立起通信连接时（还未登录前），该方法被调用。
virtual void OnRspUserLogin (CThostFtdcRspUserLoginField *pRspUserLogin, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
登录请求响应
virtual void OnRspSettlementInfoConfirm (CThostFtdcSettlementInfoConfirmField *pSettlementInfoConfirm, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
投资者结算结果确认响应
virtual void OnRspQryInstrument (CThostFtdcInstrumentField *pInstrument, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
请求查询合约响应
virtual void OnRspQryDepthMarketData (CThostFtdcDepthMarketDataField *pDepthMarketData, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
最新的合约报价
virtual void OnRspQryTradingAccount (CThostFtdcTradingAccountField *pTradingAccount, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
请求查询资金账户响应
virtual void OnRspQryInvestorPosition (CThostFtdcInvestorPositionField *pInvestorPosition, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
请求查询投资者持仓响应
virtual void OnRspOrderInsert (CThostFtdcInputOrderField *pInputOrder, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
报单录入请求响应
virtual void OnRspOrderAction (CThostFtdcInputOrderActionField *pInputOrderAction, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
报单操作请求响应
virtual void OnRspError (CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
错误应答
virtual void OnFrontDisconnected (int nReason)
当客户端与交易后台通信连接断开时，该方法被调用。当发生这个情况后，API会自动重新连接，客户端可不做处理。
virtual void OnHeartBeatWarning (int nTimeLapse)
心跳超时警告。当长时间未收到报文时，该方法被调用。
virtual void OnRtnOrder (CThostFtdcOrderField *pOrder)
报单通知
virtual void OnRtnTrade (CThostFtdcTradeField *pTrade)
成交通知
void ReqUserLogin (TThostFtdcBrokerIDType appId, TThostFtdcUserIDType userId, TThostFtdcPasswordType passwd)
用户登录请求
void ReqSettlementInfoConfirm ()
投资者结算结果确认
void ReqQryInstrument (TThostFtdcInstrumentIDType instId)
请求查询合约
void ReqQryDepthMarketData (TThostFtdcInstrumentIDType pQryDepthMarketData)
查询合约的最新报价
void ReqQryTradingAccount ()
请求查询资金账户
void ReqQryInvestorPosition (TThostFtdcInstrumentIDType instId)
请求查询投资者持仓
void ReqOrderInsert (TThostFtdcInstrumentIDType instId, TThostFtdcDirectionType dir, TThostFtdcCombOffsetFlagType kpp, TThostFtdcPriceType price, TThostFtdcVolumeType vol)
报单录入请求
void ReqOrderAction (TThostFtdcSequenceNoType orderSeq)
报单操作请求
bool IsErrorRspInfo (CThostFtdcRspInfoField *pRspInfo)
是否收到成功的响应
void PrintOrders ()
void PrintTrades ()
Public Member Functions inherited from CThostFtdcTraderSpi
virtual void OnRspAuthenticate (CThostFtdcRspAuthenticateField *pRspAuthenticateField, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
客户端认证响应
virtual void OnRspUserLogout (CThostFtdcUserLogoutField *pUserLogout, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
登出请求响应
virtual void OnRspUserPasswordUpdate (CThostFtdcUserPasswordUpdateField *pUserPasswordUpdate, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
用户口令更新请求响应
virtual void OnRspTradingAccountPasswordUpdate (CThostFtdcTradingAccountPasswordUpdateField *pTradingAccountPasswordUpdate, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
资金账户口令更新请求响应
virtual void OnRspParkedOrderInsert (CThostFtdcParkedOrderField *pParkedOrder, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
预埋单录入请求响应
virtual void OnRspParkedOrderAction (CThostFtdcParkedOrderActionField *pParkedOrderAction, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
预埋撤单录入请求响应
virtual void OnRspQueryMaxOrderVolume (CThostFtdcQueryMaxOrderVolumeField *pQueryMaxOrderVolume, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
查询最大报单数量响应
virtual void OnRspRemoveParkedOrder (CThostFtdcRemoveParkedOrderField *pRemoveParkedOrder, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
删除预埋单响应
virtual void OnRspRemoveParkedOrderAction (CThostFtdcRemoveParkedOrderActionField *pRemoveParkedOrderAction, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
删除预埋撤单响应
virtual void OnRspExecOrderInsert (CThostFtdcInputExecOrderField *pInputExecOrder, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
执行宣告录入请求响应
virtual void OnRspExecOrderAction (CThostFtdcInputExecOrderActionField *pInputExecOrderAction, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
执行宣告操作请求响应
virtual void OnRspQryOrder (CThostFtdcOrderField *pOrder, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
请求查询报单响应
virtual void OnRspQryTrade (CThostFtdcTradeField *pTrade, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
请求查询成交响应
virtual void OnRspQryInvestor (CThostFtdcInvestorField *pInvestor, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
请求查询投资者响应
virtual void OnRspQryTradingCode (CThostFtdcTradingCodeField *pTradingCode, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
请求查询交易编码响应
virtual void OnRspQryInstrumentMarginRate (CThostFtdcInstrumentMarginRateField *pInstrumentMarginRate, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
请求查询合约保证金率响应
virtual void OnRspQryInstrumentCommissionRate (CThostFtdcInstrumentCommissionRateField *pInstrumentCommissionRate, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
请求查询合约手续费率响应
virtual void OnRspQryExchange (CThostFtdcExchangeField *pExchange, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
请求查询交易所响应
virtual void OnRspQrySettlementInfo (CThostFtdcSettlementInfoField *pSettlementInfo, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
请求查询投资者结算结果响应
virtual void OnRspQryTransferBank (CThostFtdcTransferBankField *pTransferBank, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
请求查询转帐银行响应
virtual void OnRspQryInvestorPositionDetail (CThostFtdcInvestorPositionDetailField *pInvestorPositionDetail, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
请求查询投资者持仓明细响应
virtual void OnRspQryNotice (CThostFtdcNoticeField *pNotice, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
请求查询客户通知响应
virtual void OnRspQrySettlementInfoConfirm (CThostFtdcSettlementInfoConfirmField *pSettlementInfoConfirm, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
请求查询结算信息确认响应
virtual void OnRspQryInvestorPositionCombineDetail (CThostFtdcInvestorPositionCombineDetailField *pInvestorPositionCombineDetail, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
请求查询投资者持仓明细响应
virtual void OnRspQryCFMMCTradingAccountKey (CThostFtdcCFMMCTradingAccountKeyField *pCFMMCTradingAccountKey, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
查询保证金监管系统经纪公司资金账户密钥响应
virtual void OnRspQryEWarrantOffset (CThostFtdcEWarrantOffsetField *pEWarrantOffset, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
请求查询仓单折抵信息响应
virtual void OnRspQryOptionInstrTradeCost (CThostFtdcOptionInstrTradeCostField *pOptionInstrTradeCost, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
请求查询期权交易成本响应
virtual void OnRspQryOptionInstrCommRate (CThostFtdcOptionInstrCommRateField *pOptionInstrCommRate, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
请求查询期权合约手续费响应
virtual void OnRspQryExecOrder (CThostFtdcExecOrderField *pExecOrder, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
请求查询执行宣告响应
virtual void OnRspQryTransferSerial (CThostFtdcTransferSerialField *pTransferSerial, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
请求查询转帐流水响应
virtual void OnRspQryAccountregister (CThostFtdcAccountregisterField *pAccountregister, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
请求查询银期签约关系响应
virtual void OnErrRtnOrderInsert (CThostFtdcInputOrderField *pInputOrder, CThostFtdcRspInfoField *pRspInfo)
报单录入错误回报
virtual void OnErrRtnOrderAction (CThostFtdcOrderActionField *pOrderAction, CThostFtdcRspInfoField *pRspInfo)
报单操作错误回报
virtual void OnRtnInstrumentStatus (CThostFtdcInstrumentStatusField *pInstrumentStatus)
合约交易状态通知
virtual void OnRtnTradingNotice (CThostFtdcTradingNoticeInfoField *pTradingNoticeInfo)
交易通知
virtual void OnRtnErrorConditionalOrder (CThostFtdcErrorConditionalOrderField *pErrorConditionalOrder)
提示条件单校验错误
virtual void OnRtnExecOrder (CThostFtdcExecOrderField *pExecOrder)
执行宣告通知
virtual void OnErrRtnExecOrderInsert (CThostFtdcInputExecOrderField *pInputExecOrder, CThostFtdcRspInfoField *pRspInfo)
执行宣告录入错误回报
virtual void OnErrRtnExecOrderAction (CThostFtdcExecOrderActionField *pExecOrderAction, CThostFtdcRspInfoField *pRspInfo)
执行宣告操作错误回报
virtual void OnRspQryContractBank (CThostFtdcContractBankField *pContractBank, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
请求查询签约银行响应
virtual void OnRspQryParkedOrder (CThostFtdcParkedOrderField *pParkedOrder, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
请求查询预埋单响应
virtual void OnRspQryParkedOrderAction (CThostFtdcParkedOrderActionField *pParkedOrderAction, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
请求查询预埋撤单响应
virtual void OnRspQryTradingNotice (CThostFtdcTradingNoticeField *pTradingNotice, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
请求查询交易通知响应
virtual void OnRspQryBrokerTradingParams (CThostFtdcBrokerTradingParamsField *pBrokerTradingParams, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
请求查询经纪公司交易参数响应
virtual void OnRspQryBrokerTradingAlgos (CThostFtdcBrokerTradingAlgosField *pBrokerTradingAlgos, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
请求查询经纪公司交易算法响应
virtual void OnRtnFromBankToFutureByBank (CThostFtdcRspTransferField *pRspTransfer)
银行发起银行资金转期货通知
virtual void OnRtnFromFutureToBankByBank (CThostFtdcRspTransferField *pRspTransfer)
银行发起期货资金转银行通知
virtual void OnRtnRepealFromBankToFutureByBank (CThostFtdcRspRepealField *pRspRepeal)
银行发起冲正银行转期货通知
virtual void OnRtnRepealFromFutureToBankByBank (CThostFtdcRspRepealField *pRspRepeal)
银行发起冲正期货转银行通知
virtual void OnRtnFromBankToFutureByFuture (CThostFtdcRspTransferField *pRspTransfer)
期货发起银行资金转期货通知
virtual void OnRtnFromFutureToBankByFuture (CThostFtdcRspTransferField *pRspTransfer)
期货发起期货资金转银行通知
virtual void OnRtnRepealFromBankToFutureByFutureManual (CThostFtdcRspRepealField *pRspRepeal)
系统运行时期货端手工发起冲正银行转期货请求，银行处理完毕后报盘发回的通知
virtual void OnRtnRepealFromFutureToBankByFutureManual (CThostFtdcRspRepealField *pRspRepeal)
系统运行时期货端手工发起冲正期货转银行请求，银行处理完毕后报盘发回的通知
virtual void OnRtnQueryBankBalanceByFuture (CThostFtdcNotifyQueryAccountField *pNotifyQueryAccount)
期货发起查询银行余额通知
virtual void OnErrRtnBankToFutureByFuture (CThostFtdcReqTransferField *pReqTransfer, CThostFtdcRspInfoField *pRspInfo)
期货发起银行资金转期货错误回报
virtual void OnErrRtnFutureToBankByFuture (CThostFtdcReqTransferField *pReqTransfer, CThostFtdcRspInfoField *pRspInfo)
期货发起期货资金转银行错误回报
virtual void OnErrRtnRepealBankToFutureByFutureManual (CThostFtdcReqRepealField *pReqRepeal, CThostFtdcRspInfoField *pRspInfo)
系统运行时期货端手工发起冲正银行转期货错误回报
virtual void OnErrRtnRepealFutureToBankByFutureManual (CThostFtdcReqRepealField *pReqRepeal, CThostFtdcRspInfoField *pRspInfo)
系统运行时期货端手工发起冲正期货转银行错误回报
virtual void OnErrRtnQueryBankBalanceByFuture (CThostFtdcReqQueryAccountField *pReqQueryAccount, CThostFtdcRspInfoField *pRspInfo)
期货发起查询银行余额错误回报
virtual void OnRtnRepealFromBankToFutureByFuture (CThostFtdcRspRepealField *pRspRepeal)
期货发起冲正银行转期货请求，银行处理完毕后报盘发回的通知
virtual void OnRtnRepealFromFutureToBankByFuture (CThostFtdcRspRepealField *pRspRepeal)
期货发起冲正期货转银行请求，银行处理完毕后报盘发回的通知
virtual void OnRspFromBankToFutureByFuture (CThostFtdcReqTransferField *pReqTransfer, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
期货发起银行资金转期货应答
virtual void OnRspFromFutureToBankByFuture (CThostFtdcReqTransferField *pReqTransfer, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
期货发起期货资金转银行应答
virtual void OnRspQueryBankAccountMoneyByFuture (CThostFtdcReqQueryAccountField *pReqQueryAccount, CThostFtdcRspInfoField *pRspInfo, int nRequestID, bool bIsLast)
期货发起查询银行余额应答
virtual void OnRtnOpenAccountByBank (CThostFtdcOpenAccountField *pOpenAccount)
银行发起银期开户通知
virtual void OnRtnCancelAccountByBank (CThostFtdcCancelAccountField *pCancelAccount)
银行发起银期销户通知
virtual void OnRtnChangeAccountByBank (CThostFtdcChangeAccountField *pChangeAccount)
银行发起变更银行账号通知
Private Attributes
CThostFtdcTraderApi * pUserApi
Detailed Description
Definition at line 6 of file CtpTraderSpi.h.
Constructor & Destructor Documentation
CtpTraderSpi::CtpTraderSpi (CThostFtdcTraderApi * api) inline
Definition at line 9 of file CtpTraderSpi.h.
:pUserApi(api){};
Member Function Documentation
bool CtpTraderSpi::IsErrorRspInfo (CThostFtdcRspInfoField * pRspInfo)
是否收到成功的响应
Definition at line 325 of file CtpTraderSpi.cpp.
References CThostFtdcRspInfoField::ErrorID, and CThostFtdcRspInfoField::ErrorMsg.
{
    // 如果ErrorID != 0, 说明收到了错误的响应
    bool ret = ((pRspInfo) && (pRspInfo->ErrorID != 0));
  if (ret){
    cerr<<" 响应 | "<<pRspInfo->ErrorMsg<<endl;
  }
    return ret;
}
void CtpTraderSpi::OnFrontConnected () virtual
当客户端与交易后台建立起通信连接时（还未登录前），该方法被调用。
Reimplemented from CThostFtdcTraderSpi.
Definition at line 33 of file CtpTraderSpi.cpp.
References sem, and CSem::sem_v().
{
    cerr<<" 连接交易前置...成功"<<endl;
    ReqUserLogin("1035", "00000071", "123456");
    sem.sem_v();
}
void CtpTraderSpi::OnFrontDisconnected (int nReason) virtual
当客户端与交易后台通信连接断开时，该方法被调用。当发生这个情况后，API会自动重新连接，客户端可不做处理。
Reimplemented from CThostFtdcTraderSpi.
Definition at line 308 of file CtpTraderSpi.cpp.
{
    cerr<<" 响应 | 连接中断..."
      << " reason=" << nReason << endl;
}
void CtpTraderSpi::OnHeartBeatWarning (int nTimeLapse) virtual
心跳超时警告。当长时间未收到报文时，该方法被调用。
Reimplemented from CThostFtdcTraderSpi.
Definition at line 314 of file CtpTraderSpi.cpp.
{
    cerr<<" 响应 | 心跳超时警告..."
      << " TimerLapse = " << nTimeLapse << endl;
}
void CtpTraderSpi::OnRspError (CThostFtdcRspInfoField * pRspInfo, int nRequestID, bool bIsLast) virtual
错误应答
Reimplemented from CThostFtdcTraderSpi.
Definition at line 320 of file CtpTraderSpi.cpp.
{
    IsErrorRspInfo(pRspInfo);
}
void CtpTraderSpi::OnRspOrderAction (CThostFtdcInputOrderActionField * pInputOrderAction, CThostFtdcRspInfoField * pRspInfo, int nRequestID, bool bIsLast) virtual
报单操作请求响应
Reimplemented from CThostFtdcTraderSpi.
Definition at line 262 of file CtpTraderSpi.cpp.
References CThostFtdcInputOrderActionField::ExchangeID, CThostFtdcInputOrderActionField::OrderSysID, sem, and CSem::sem_v().
{
  if (!IsErrorRspInfo(pRspInfo) && pInputOrderAction){
    cerr<< " 响应 | 撤单成功..."
      << "交易所:"<<pInputOrderAction->ExchangeID
      <<" 报单编号:"<<pInputOrderAction->OrderSysID<<endl;
  }
  if(bIsLast) sem.sem_v();
}
void CtpTraderSpi::OnRspOrderInsert (CThostFtdcInputOrderField * pInputOrder, CThostFtdcRspInfoField * pRspInfo, int nRequestID, bool bIsLast) virtual
报单录入请求响应
Reimplemented from CThostFtdcTraderSpi.
Definition at line 230 of file CtpTraderSpi.cpp.
References CThostFtdcInputOrderField::OrderRef, sem, and CSem::sem_v().
{
  if( !IsErrorRspInfo(pRspInfo) && pInputOrder ){
    cerr<<"响应 | 报单提交成功...报单引用:"<<pInputOrder->OrderRef<<endl;
  }
  if(bIsLast) sem.sem_v();
}
void CtpTraderSpi::OnRspQryDepthMarketData (CThostFtdcDepthMarketDataField * pDepthMarketData, CThostFtdcRspInfoField * pRspInfo, int nRequestID, bool bIsLast) virtual
最新的合约报价
Reimplemented from CThostFtdcTraderSpi.
Definition at line 126 of file CtpTraderSpi.cpp.
References CThostFtdcDepthMarketDataField::BidPrice1, CThostFtdcDepthMarketDataField::InstrumentID, sem, and CSem::sem_v().
{
    if ( !IsErrorRspInfo(pRspInfo) && pDepthMarketData){
    cerr<<" 响应 | 合约:"<<pDepthMarketData->InstrumentID<<endl
        <<"申买价一:"<<pDepthMarketData->BidPrice1 <<endl;
  }
  if(bIsLast) sem.sem_v();
}
void CtpTraderSpi::OnRspQryInstrument (CThostFtdcInstrumentField * pInstrument, CThostFtdcRspInfoField * pRspInfo, int nRequestID, bool bIsLast) virtual
请求查询合约响应
Reimplemented from CThostFtdcTraderSpi.
Definition at line 103 of file CtpTraderSpi.cpp.
References CThostFtdcInstrumentField::DeliveryMonth, CThostFtdcInstrumentField::ExchangeID, CThostFtdcInstrumentField::InstrumentID, CThostFtdcInstrumentField::LongMarginRatio, sem, CSem::sem_v(), and CThostFtdcInstrumentField::ShortMarginRatio.
{
    if ( !IsErrorRspInfo(pRspInfo) &&  pInstrument){
    cerr<<" 响应 | 合约:"<<pInstrument->InstrumentID
      <<" 交割月:"<<pInstrument->DeliveryMonth
      <<" 多头保证金率:"<<pInstrument->LongMarginRatio
      <<" 交易所代码:"<<pInstrument->ExchangeID
      <<" 空头保证金率:"<<pInstrument->ShortMarginRatio<<endl;
  }
  if(bIsLast) sem.sem_v();
}
void CtpTraderSpi::OnRspQryInvestorPosition (CThostFtdcInvestorPositionField * pInvestorPosition, CThostFtdcRspInfoField * pRspInfo, int nRequestID, bool bIsLast) virtual
请求查询投资者持仓响应
Reimplemented from CThostFtdcTraderSpi.
Definition at line 176 of file CtpTraderSpi.cpp.
References CThostFtdcInvestorPositionField::InstrumentID, MapDirection(), CThostFtdcInvestorPositionField::PosiDirection, CThostFtdcInvestorPositionField::Position, CThostFtdcInvestorPositionField::PositionProfit, sem, CSem::sem_v(), CThostFtdcInvestorPositionField::TodayPosition, CThostFtdcInvestorPositionField::UseMargin, and CThostFtdcInvestorPositionField::YdPosition.
{
  if( !IsErrorRspInfo(pRspInfo) &&  pInvestorPosition ){
    cerr<<" 响应 | 合约:"<<pInvestorPosition->InstrumentID
      <<" 方向:"<<MapDirection(pInvestorPosition->PosiDirection-2,false)
      <<" 总持仓:"<<pInvestorPosition->Position
      <<" 昨仓:"<<pInvestorPosition->YdPosition
      <<" 今仓:"<<pInvestorPosition->TodayPosition
      <<" 持仓盈亏:"<<pInvestorPosition->PositionProfit
      <<" 保证金:"<<pInvestorPosition->UseMargin<<endl;
  }
  if(bIsLast) sem.sem_v();
}
void CtpTraderSpi::OnRspQryTradingAccount (CThostFtdcTradingAccountField * pTradingAccount, CThostFtdcRspInfoField * pRspInfo, int nRequestID, bool bIsLast) virtual
请求查询资金账户响应
Reimplemented from CThostFtdcTraderSpi.
Definition at line 147 of file CtpTraderSpi.cpp.
References CThostFtdcTradingAccountField::Available, CThostFtdcTradingAccountField::Balance, CThostFtdcTradingAccountField::CloseProfit, CThostFtdcTradingAccountField::Commission, CThostFtdcTradingAccountField::CurrMargin, CThostFtdcTradingAccountField::FrozenMargin, CThostFtdcTradingAccountField::PositionProfit, sem, and CSem::sem_v().
{
    if (!IsErrorRspInfo(pRspInfo) &&  pTradingAccount){
    cerr<<" 响应 | 权益:"<<pTradingAccount->Balance
      <<" 可用:"<<pTradingAccount->Available
      <<" 保证金:"<<pTradingAccount->CurrMargin
      <<" 平仓盈亏:"<<pTradingAccount->CloseProfit
      <<" 持仓盈亏"<<pTradingAccount->PositionProfit
      <<" 手续费:"<<pTradingAccount->Commission
      <<" 冻结保证金:"<<pTradingAccount->FrozenMargin
      //<<" 冻结手续费:"<<pTradingAccount->FrozenCommission
      << endl;
  }
  if(bIsLast) sem.sem_v();
}
void CtpTraderSpi::OnRspSettlementInfoConfirm (CThostFtdcSettlementInfoConfirmField * pSettlementInfoConfirm, CThostFtdcRspInfoField * pRspInfo, int nRequestID, bool bIsLast) virtual
投资者结算结果确认响应
Reimplemented from CThostFtdcTraderSpi.
Definition at line 81 of file CtpTraderSpi.cpp.
References CThostFtdcSettlementInfoConfirmField::ConfirmDate, CThostFtdcSettlementInfoConfirmField::ConfirmTime, CThostFtdcSettlementInfoConfirmField::InvestorID, sem, and CSem::sem_v().
{
    if( !IsErrorRspInfo(pRspInfo) && pSettlementInfoConfirm){
    cerr<<" 响应 | 结算单..."<<pSettlementInfoConfirm->InvestorID
      <<"...<"<<pSettlementInfoConfirm->ConfirmDate
      <<" "<<pSettlementInfoConfirm->ConfirmTime<<">...确认"<<endl;
  }
  if(bIsLast) sem.sem_v();
}
void CtpTraderSpi::OnRspUserLogin (CThostFtdcRspUserLoginField * pRspUserLogin, CThostFtdcRspInfoField * pRspInfo, int nRequestID, bool bIsLast) virtual
登录请求响应
Reimplemented from CThostFtdcTraderSpi.
Definition at line 54 of file CtpTraderSpi.cpp.
References frontId, CThostFtdcRspUserLoginField::FrontID, CThostFtdcRspUserLoginField::MaxOrderRef, orderRef, sem, CSem::sem_v(), sessionId, CThostFtdcRspUserLoginField::SessionID, and CThostFtdcRspUserLoginField::TradingDay.
{
    if ( !IsErrorRspInfo(pRspInfo) && pRspUserLogin ) {
    // 保存会话参数
        frontId = pRspUserLogin->FrontID;
        sessionId = pRspUserLogin->SessionID;
        int nextOrderRef = atoi(pRspUserLogin->MaxOrderRef);
        sprintf(orderRef, "%d", ++nextOrderRef);
       cerr<<" 响应 | 登录成功...当前交易日:"
       <<pRspUserLogin->TradingDay<<endl;
        char *ru = "";
        ReqQryInstrument(ru);
  }
  if(bIsLast) sem.sem_v();
}
void CtpTraderSpi::OnRtnOrder (CThostFtdcOrderField * pOrder) virtual
报单通知
报单回报
Reimplemented from CThostFtdcTraderSpi.
Definition at line 275 of file CtpTraderSpi.cpp.
References CThostFtdcOrderField::BrokerOrderSeq, orderList, sem, and CSem::sem_v().
{
  CThostFtdcOrderField* order = new CThostFtdcOrderField();
  memcpy(order,  pOrder, sizeof(CThostFtdcOrderField));
  bool founded=false;    unsigned int i=0;
  for(i=0; i<orderList.size(); i++){
    if(orderList[i]->BrokerOrderSeq == order->BrokerOrderSeq) {
      founded=true;    break;
    }
  }
  if(founded) orderList[i]= order;
  else  orderList.push_back(order);
  cerr<<" 回报 | 报单已提交...序号:"<<order->BrokerOrderSeq<<endl;
  sem.sem_v();
}
void CtpTraderSpi::OnRtnTrade (CThostFtdcTradeField * pTrade) virtual
成交通知
Reimplemented from CThostFtdcTraderSpi.
Definition at line 292 of file CtpTraderSpi.cpp.
References sem, CSem::sem_v(), CThostFtdcTradeField::TradeID, and tradeList.
{
  CThostFtdcTradeField* trade = new CThostFtdcTradeField();
  memcpy(trade,  pTrade, sizeof(CThostFtdcTradeField));
  bool founded=false;     unsigned int i=0;
  for(i=0; i<tradeList.size(); i++){
    if(tradeList[i]->TradeID == trade->TradeID) {
      founded=true;   break;
    }
  }
  if(founded) tradeList[i] = trade;
  else  tradeList.push_back(trade);
  cerr<<" 回报 | 报单已成交...成交编号:"<<trade->TradeID<<endl;
  sem.sem_v();
}
void CtpTraderSpi::PrintOrders ()
Definition at line 335 of file CtpTraderSpi.cpp.
References CThostFtdcOrderField::BrokerOrderSeq, CThostFtdcOrderField::CombOffsetFlag, CThostFtdcOrderField::Direction, CThostFtdcOrderField::InstrumentID, CThostFtdcOrderField::LimitPrice, MapDirection(), MapOffset(), orderList, CThostFtdcOrderField::OrderSysID, sem, CSem::sem_v(), CThostFtdcOrderField::StatusMsg, and CThostFtdcOrderField::VolumeTotalOriginal.
{
  CThostFtdcOrderField* pOrder;
  for(unsigned int i=0; i<orderList.size(); i++){
    pOrder = orderList[i];
    cerr<<" 报单 | 合约:"<<pOrder->InstrumentID
      <<" 方向:"<<MapDirection(pOrder->Direction,false)
      <<" 开平:"<<MapOffset(pOrder->CombOffsetFlag[0],false)
      <<" 价格:"<<pOrder->LimitPrice
      <<" 数量:"<<pOrder->VolumeTotalOriginal
      <<" 序号:"<<pOrder->BrokerOrderSeq
      <<" 报单编号:"<<pOrder->OrderSysID
      <<" 状态:"<<pOrder->StatusMsg<<endl;
  }
  sem.sem_v();
}
void CtpTraderSpi::PrintTrades ()
Definition at line 350 of file CtpTraderSpi.cpp.
References CThostFtdcTradeField::Direction, CThostFtdcTradeField::InstrumentID, MapDirection(), MapOffset(), CThostFtdcTradeField::OffsetFlag, CThostFtdcTradeField::OrderSysID, CThostFtdcTradeField::Price, sem, CSem::sem_v(), CThostFtdcTradeField::TradeID, tradeList, and CThostFtdcTradeField::Volume.
{
  CThostFtdcTradeField* pTrade;
  for(unsigned int i=0; i<tradeList.size(); i++){
    pTrade = tradeList[i];
    cerr<<" 成交 | 合约:"<< pTrade->InstrumentID
      <<" 方向:"<<MapDirection(pTrade->Direction,false)
      <<" 开平:"<<MapOffset(pTrade->OffsetFlag,false)
      <<" 价格:"<<pTrade->Price
      <<" 数量:"<<pTrade->Volume
      <<" 报单编号:"<<pTrade->OrderSysID
      <<" 成交编号:"<<pTrade->TradeID<<endl;
  }
  sem.sem_v();
}
void CtpTraderSpi::ReqOrderAction (TThostFtdcSequenceNoType orderSeq)
报单操作请求
Definition at line 239 of file CtpTraderSpi.cpp.
References CThostFtdcInputOrderActionField::ActionFlag, appId, CThostFtdcInputOrderActionField::BrokerID, CThostFtdcInputOrderActionField::ExchangeID, CThostFtdcInputOrderActionField::InvestorID, orderList, CThostFtdcInputOrderActionField::OrderSysID, requestId, THOST_FTDC_AF_Delete, and userId.
{
  bool found=false; unsigned int i=0;
  for(i=0;i<orderList.size();i++){
    if(orderList[i]->BrokerOrderSeq == orderSeq){ found = true; break;}
  }
  if(!found){cerr<<" 请求 | 报单不存在."<<endl; return;}
    CThostFtdcInputOrderActionField req;
    memset(&req, 0, sizeof(req));
    strcpy(req.BrokerID, appId);   //经纪公司代码
    strcpy(req.InvestorID, userId); //投资者代码
    //strcpy(req.OrderRef, pOrderRef); //报单引用
    //req.FrontID = frontId;           //前置编号
    //req.SessionID = sessionId;       //会话编号
  strcpy(req.ExchangeID, orderList[i]->ExchangeID);
  strcpy(req.OrderSysID, orderList[i]->OrderSysID);
    req.ActionFlag = THOST_FTDC_AF_Delete;  //操作标志
    int ret = pUserApi->ReqOrderAction(&req, ++requestId);
    cerr<< " 请求 | 发送撤单..." <<((ret == 0)?"成功":"失败") << endl;
}
void CtpTraderSpi::ReqOrderInsert (TThostFtdcInstrumentIDType instId, TThostFtdcDirectionType dir, TThostFtdcCombOffsetFlagType kpp, TThostFtdcPriceType price, TThostFtdcVolumeType vol)
报单录入请求
数量
Definition at line 192 of file CtpTraderSpi.cpp.
References appId, CThostFtdcInputOrderField::BrokerID, CThostFtdcInputOrderField::CombHedgeFlag, CThostFtdcInputOrderField::CombOffsetFlag, CThostFtdcInputOrderField::ContingentCondition, CThostFtdcInputOrderField::Direction, CThostFtdcInputOrderField::ForceCloseReason, CThostFtdcInputOrderField::InstrumentID, CThostFtdcInputOrderField::InvestorID, CThostFtdcInputOrderField::IsAutoSuspend, CThostFtdcInputOrderField::LimitPrice, MapDirection(), MapOffset(), CThostFtdcInputOrderField::MinVolume, CThostFtdcInputOrderField::OrderPriceType, orderRef, CThostFtdcInputOrderField::OrderRef, requestId, THOST_FTDC_CC_Immediately, THOST_FTDC_FCC_NotForceClose, THOST_FTDC_HF_Speculation, THOST_FTDC_OPT_AnyPrice, THOST_FTDC_OPT_LimitPrice, THOST_FTDC_TC_GFD, THOST_FTDC_TC_IOC, THOST_FTDC_VC_AV, CThostFtdcInputOrderField::TimeCondition, CThostFtdcInputOrderField::UserForceClose, userId, CThostFtdcInputOrderField::VolumeCondition, and CThostFtdcInputOrderField::VolumeTotalOriginal.
{
    CThostFtdcInputOrderField req;
    memset(&req, 0, sizeof(req));
    strcpy(req.BrokerID, appId);  //应用单元代码
    strcpy(req.InvestorID, userId); //投资者代码
    strcpy(req.InstrumentID, instId); //合约代码
    strcpy(req.OrderRef, orderRef);  //报单引用
  int nextOrderRef = atoi(orderRef);
  sprintf(orderRef, "%d", ++nextOrderRef);
  req.LimitPrice = price;   //价格
  if(0==req.LimitPrice){
      req.OrderPriceType = THOST_FTDC_OPT_AnyPrice;//价格类型=市价
      req.TimeCondition = THOST_FTDC_TC_IOC;//有效期类型:立即完成，否则撤销
  }else{
    req.OrderPriceType = THOST_FTDC_OPT_LimitPrice;//价格类型=限价
    req.TimeCondition = THOST_FTDC_TC_GFD;  //有效期类型:当日有效
  }
  req.Direction = MapDirection(dir,true);  //买卖方向
    req.CombOffsetFlag[0] = MapOffset(kpp[0],true); //组合开平标志:开仓
    req.CombHedgeFlag[0] = THOST_FTDC_HF_Speculation;     //组合投机套保标志
    req.VolumeTotalOriginal = vol;
    req.VolumeCondition = THOST_FTDC_VC_AV; //成交量类型:任何数量
    req.MinVolume = 1;  //最小成交量:1
    req.ContingentCondition = THOST_FTDC_CC_Immediately;  //触发条件:立即
  //TThostFtdcPriceType StopPrice;  //止损价
    req.ForceCloseReason = THOST_FTDC_FCC_NotForceClose;    //强平原因:非强平
    req.IsAutoSuspend = 0;  //自动挂起标志:否
    req.UserForceClose = 0;   //用户强评标志:否
    int ret = pUserApi->ReqOrderInsert(&req, ++requestId);
    cerr<<" 请求 | 发送报单..."<<((ret == 0)?"成功":"失败")<< endl;
}
void CtpTraderSpi::ReqQryDepthMarketData (TThostFtdcInstrumentIDType pQryDepthMarketData)
查询合约的最新报价
Definition at line 116 of file CtpTraderSpi.cpp.
References CThostFtdcQryDepthMarketDataField::InstrumentID, and requestId.
{
    CThostFtdcQryDepthMarketDataField req;
    memset(&req, 0, sizeof(req));
    strcpy(req.InstrumentID, instId);//为空表示查询所有合约
    int ret = pUserApi->ReqQryDepthMarketData(&req, ++requestId);
    cerr<<" 请求 | 发送合约报价查询..."<<((ret == 0)?"成功":"失败")<<endl;
    cerr<<ret<<endl;
}
void CtpTraderSpi::ReqQryInstrument (TThostFtdcInstrumentIDType instId)
请求查询合约
Definition at line 93 of file CtpTraderSpi.cpp.
References CThostFtdcQryInstrumentField::InstrumentID, and requestId.
{
    CThostFtdcQryInstrumentField req;
    memset(&req, 0, sizeof(req));
    strcpy(req.InstrumentID, instId);//为空表示查询所有合约
    int ret = pUserApi->ReqQryInstrument(&req, ++requestId);
    cerr<<" 请求 | 发送合约查询..."<<((ret == 0)?"成功":"失败")<<endl;
    cerr<<ret<<endl;
}
void CtpTraderSpi::ReqQryInvestorPosition (TThostFtdcInstrumentIDType instId)
请求查询投资者持仓
Definition at line 165 of file CtpTraderSpi.cpp.
References appId, CThostFtdcQryInvestorPositionField::BrokerID, CThostFtdcQryInvestorPositionField::InstrumentID, CThostFtdcQryInvestorPositionField::InvestorID, requestId, and userId.
{
    CThostFtdcQryInvestorPositionField req;
    memset(&req, 0, sizeof(req));
    strcpy(req.BrokerID, appId);
    strcpy(req.InvestorID, userId);
    strcpy(req.InstrumentID, instId);
    int ret = pUserApi->ReqQryInvestorPosition(&req, ++requestId);
    cerr<<" 请求 | 发送持仓查询..."<<((ret == 0)?"成功":"失败")<<endl;
}
void CtpTraderSpi::ReqQryTradingAccount ()
请求查询资金账户
Definition at line 136 of file CtpTraderSpi.cpp.
References appId, CThostFtdcQryTradingAccountField::BrokerID, CThostFtdcQryTradingAccountField::InvestorID, requestId, and userId.
{
    CThostFtdcQryTradingAccountField req;
    memset(&req, 0, sizeof(req));
    strcpy(req.BrokerID, appId);
    strcpy(req.InvestorID, userId);
    int ret = pUserApi->ReqQryTradingAccount(&req, ++requestId);
    cerr<<" 请求 | 发送资金查询..."<<((ret == 0)?"成功":"失败")<<endl;
}
void CtpTraderSpi::ReqSettlementInfoConfirm ()
投资者结算结果确认
Definition at line 71 of file CtpTraderSpi.cpp.
References appId, CThostFtdcSettlementInfoConfirmField::BrokerID, CThostFtdcSettlementInfoConfirmField::InvestorID, requestId, and userId.
{
    CThostFtdcSettlementInfoConfirmField req;
    memset(&req, 0, sizeof(req));
    strcpy(req.BrokerID, appId);
    strcpy(req.InvestorID, userId);
    int ret = pUserApi->ReqSettlementInfoConfirm(&req, ++requestId);
    cerr<<" 请求 | 发送结算单确认..."<<((ret == 0)?"成功":"失败")<<endl;
}
void CtpTraderSpi::ReqUserLogin (TThostFtdcBrokerIDType appId, TThostFtdcUserIDType userId, TThostFtdcPasswordType passwd)
用户登录请求
Definition at line 41 of file CtpTraderSpi.cpp.
References appId, CThostFtdcReqUserLoginField::BrokerID, CThostFtdcReqUserLoginField::Password, requestId, userId, and CThostFtdcReqUserLoginField::UserID.
{
    CThostFtdcReqUserLoginField req;
    memset(&req, 0, sizeof(req));
    strcpy(req.BrokerID, vAppId); strcpy(appId, vAppId);
    strcpy(req.UserID, vUserId);  strcpy(userId, vUserId);
    strcpy(req.Password, vPasswd);
    int ret = pUserApi->ReqUserLogin(&req, ++requestId);
    cerr<<" sending | 发送登录..."<<((ret == 0) ? "成功" :"失败") << endl;
}
Member Data Documentation
CThostFtdcTraderApi* CtpTraderSpi::pUserApi private
Definition at line 82 of file CtpTraderSpi.h.
The documentation for this class was generated from the following files:
CtpTraderSpi.h
CtpTraderSpi.cpp